### ISSUE TITLE
Help with the creation of an OTF-SVG

### ISSUE THREAD

**Issue by 00sapo** [adobe-type-tools/opentype-svg#28]
I am opening this issue only because I think you can really help me with this problem. Basically, I have an SVG an OTF font and I want to attach the SVG to the font programmatically. For this, I'm using `opentype-svg` and `fonttools`, but the final font contains badly scaled glyphs. 

Here the problem is explained in more details. Here is the source code for reproducing the issue: [Archive.zip](https://github.com/adobe-type-tools/opentype-svg/files/12187336/Archive.zip)

### 1. Dummy Font Creation
First, I create a dummy font having dummy glyphs. In this example, only the glyph `a` is created. For this, I use fontforge.

To run the script, install fontforge and python and run `fontforge -script example_dummy.py`. A file named `DummyFont.otf` will be created. It's also attached in the zip.

### 2. Attaching SVG Files
The second step is to attach SVG files in the SVG table of the font. As suggested by opentypesvg tool, I remove both widht and height, as well as the viewport property of the `<svg>` tag. The problem is that the SVGs are not rescaled properly. In both LuaTeX and Inkscape, they appear to have a small size compared to the glyph viewport. Below are two screenshots of the result.

To run the script, run `pip install opentypesvg fonttools` and then `python example_svg.py`. A file named `DummyFontSvg.otf` will be created. It's also attached in the zip.

### 3. Result

**Terminal output:** (note that SVG and font have the same viewport and that font is correctly validated by fontforge)
![screenshot_terminal](https://github.com/adobe-type-tools/opentype-svg/assets/22996003/00a43751-d6ca-44e9-a674-cae6ac6aa02b)

**Inkscape:** (the green background is the text-selection color of one character, it shows the maximum size a glyph can have)
![Screenshot_inkscape](https://github.com/adobe-type-tools/opentype-svg/assets/22996003/5322758d-f218-4ac1-b4b4-1139d9daa6db)

**LuaLaTeX PDF:**
![screenshot_latex](https://github.com/adobe-type-tools/opentype-svg/assets/22996003/3bc18657-12f5-458c-8d62-ebf8d7923f43)

**Comment by miguelsousa** [comment]
Hi Frederico,

To assemble the OT-SVG font you're using your own scripts, as opposed to using the ones provided with `opentype-svg`, so my ability to help you is limited.

I also don't know how well Inkscape or LuaLaTeX PDF support OpenType-SVG fonts. It's possible that the issues you're facing are caused by bugs in those applications, rather than problems with your font.

Having said that, I'll mention a few points that might help you with your project:

- To create the base font, you can use FontTools' [FontBuilder](https://github.com/fonttools/fonttools/blob/main/Lib/fontTools/fontBuilder.py)
- In general, removing the `viewBox`, `width`, and `height` parameters from the SVG file helps with fixing scaling and positioning problems. But this assumes that 1) the SVG artwork was designed at the same scale as the font's unitsPerEm, and 2) the SVG artwork is positioned on the canvas in a way that aligns with the font's origin coordinates (i.e. baseline and left sidebearing).
- When I delete  the `viewBox`, `width`, and `height` parameters from your **a.svg** file and open it in Adobe Illustrator, I see the artwork way off canvas (screenshot below). The baseline of the **a** should be touching the top of the page, and the whole letter needs to be moved to the left, in order to be closer to the page's origin (see second screenshot, and notice the rulers). 
- To fix the sizing problem, you either scale up the artwork to closely match the font's unitsPerEm value, OR you reduce the font's unitsPerEm value to more closely match the size of the SVG artwork.

<img width="664" alt="Ai-a" src="https://github.com/adobe-type-tools/opentype-svg/assets/2119742/7ebabf22-cc29-4339-ad21-87fd50ab3fe7">
<img width="502" alt="a-moved" src="https://github.com/adobe-type-tools/opentype-svg/assets/2119742/e1f65cf4-76f9-465e-9923-3f08d5e17e2f">

**Comment by 00sapo** [comment]
Thank you so much. I still don't have a clear rule to follow for rescaling the images, but your words pointed me towards a rule of thumbs that works in my case. I managed to obtain a meaningful size by transposing and rescaling the SVG using a transform attribute and then applying the transform attribute to each inner object using an Inkscape extension (without using Inkscape, actually, only its python extension module `inkex`)

**Comment by miguelsousa** [comment]
cross-linking: https://github.com/fonttools/fonttools/discussions/3229
